### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by cvpeck** [jemstelos/obsidian-media-notes#37]
Macos 15.0.1
Obsidian 1.7.4

`
Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
app.js:1 Plugin failure: media-notes 
TypeError: Cannot read properties of undefined (reading 'length')
    at app.js:1:842801
    at KM (app.js:1:842873)
    at _T (app.js:1:1183218)
    at MediaNotesPlugin.renderPlayerInView (plugin:media-notes:26567:63)
    at eval (plugin:media-notes:26673:12)
    at Array.forEach (<anonymous>)
    at MediaNotesPlugin.onload (plugin:media-notes:26671:52)
127.0.0.1:8765/:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
app.js:1 Plugin failure: media-notes 
TypeError: Cannot read properties of undefined (reading 'length')
    at app.js:1:842801
    at KM (app.js:1:842873)
    at _T (app.js:1:1183218)
    at MediaNotesPlugin.renderPlayerInView (plugin:media-notes:26567:63)
    at eval (plugin:media-notes:26673:12)
    at Array.forEach (<anonymous>)
    at MediaNotesPlugin.onload (plugin:media-notes:26671:52)
`

**Comment by cvpeck** [comment]
That is the developer console after trying to start the plugin. Vault has a page with media_link to https://www.youtube.com/watch?v=eILVzTNWnq8&list=PLnsHyLR3BOeiB_GOkbMerJVemNUrAPll3&t=562
saved from bookmarklet

**Comment by zenus260** [comment]
Also experiencing this problem on Windows

**Comment by GustavoSZ124** [comment]
When the plugin is loaded, it attempts to read the frontmatter of all open notes, but it is not properly validated, which causes the error.

A temporary solution is to close all notes and then activate the plugin. Once it is successfully activated, the error no longer occurs.

**Comment by fgsanz** [comment]
Hi, I have the same problem and workaround does NOT solve the issue. This is what I did to isolate the issue:

- I shut down Obsidian
- I have renamed the file ./obsidian/community-plugins.json (so no file is found)
- I have renamed the directory ./obsidian/plugins (so no directory is found)
- I launched Obsidian
- I made sure of having no notes opened, at all
- I then installed “Media notes” plugin

… and it failed to start see screenshot below

<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/a2f39e0c-cd35-4a43-a3ac-6004b205faec" />

Please help! 🙏

**Comment by fgsanz** [comment]
Is this the same problem? Should I open a new (separate) bug report?

**Comment by Mohammed-Alama** [comment]
Heey 
I have forked the repo and make the fix and i have add a deploy script that load this plugins as it's a custom one
change the dir of your vault https://github.com/Mohammed-Alama/obsidian-media-notes , please try it out and give me a feedback

**Comment by gmmazza** [comment]
Thank you for your fix, @Mohammed-Alama 
I don't know how to do what you say. 
Please, can you make it a little easier for those not technically able to understand it?

**Comment by Mohammed-Alama** [comment]
You will need to clone the repo whatever place and then change the vault path to your own and then run `make deploy`
this how the script look like 
<img width="863" height="578" alt="Image" src="https://github.com/user-attachments/assets/d7098164-0930-4e67-bd78-5c88cc713f93" />

**Comment by robster7674** [comment]
@Mohammed-Alama did you end up fixing this in your fork?
